FROM centos
ENV LANG C.UTF-8
# 指定容器内jdk所在目录
ENV JAVA_HOME /usr/local/software/jdk1.8.0_212
ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
ENV PATH $PATH:$JAVA_HOME/bin:$JAVA_HOME/sbin
EXPOSE 5558

CMD ["sh","/home/ykz_leader/server/shell/leader.sh"]