spring:
  profiles:
    active: @env@
  application:
    name: xxx-project
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    servlet:
      load-on-startup: 0
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
