spring:
  main:
    allow-circular-references: true
  profiles:
    active: @env@
  application:
    name: xxx-project
  jackson:
    # 不为空的属性才会序列化,具体属性可看JsonInclude.Include
    default-property-inclusion: non_null
    # 设置全局时区
    time-zone: GMT+8
    serialization:
      # 返回的java.util.date转换成timestamp
      WRITE_DATES_AS_TIMESTAMPS: true
      # 对象为空时是否报错，默认true
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false

  mvc:
    servlet:
      load-on-startup: 0
    #出现错误时, 直接抛出异常
    throw-exception-if-no-handler-found: true
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: @datasource.url@
    username: @datasource.username@
    password: @datasource.password@
    driver-class-name: @datasource.driver@
    # 连接池
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
  level:
    com.zenith.xxx.dao: debug

custom:
  log:
    level: @log-level@
    path: @log-path@
  swagger:
    enable: @swagger-enable@
com:
  efficient:
    swagger:
      enable: true
      version: 1.0.1
      description: "测试工程描述"
      title: "测试工程"

